"""Status and flag vocabulary shared by lifecycle, analysis and report."""

# Rep statuses (terminal).
SUCCESS = "SUCCESS"
INVALID_BASELINE = "INVALID_BASELINE"
FAILED_INPUT = "FAILED_INPUT"
FAILED_ERRORS = "FAILED_ERRORS"
FAILED_CRASH = "FAILED_CRASH"
FAILED_TIMEOUT = "FAILED_TIMEOUT"
FAILED_OOM = "FAILED_OOM"
FAILED_TOKENS = "FAILED_TOKENS"          # completion_tokens != output_len for > 1% of requests
UNSTABLE_DRIFT = "UNSTABLE_DRIFT"
INVALID_PINNING = "INVALID_PINNING"
INVALID_SAMPLER = "INVALID_SAMPLER"      # sampler missed > 1% of samples during measurement

REP_STATUSES = {
    SUCCESS, INVALID_BASELINE, FAILED_INPUT, FAILED_ERRORS, FAILED_CRASH, FAILED_TIMEOUT,
    FAILED_OOM, FAILED_TOKENS, UNSTABLE_DRIFT, INVALID_PINNING, INVALID_SAMPLER,
}

# Server-config level statuses.
INVALID_SYSTEM = "INVALID_SYSTEM"
FAILED_SERVER_START = "FAILED_SERVER_START"
INVALID_ENV_CHANGED = "INVALID_ENV_CHANGED"
INVALID_BACKEND = "INVALID_BACKEND"     # detected backend contradicts the config's accel setting
CONFIG_DONE = "DONE"

# Rep flags (non-fatal).
WARN_MEM_GROWTH = "WARN_MEM_GROWTH"
WARN_SLOW_RECOVERY = "WARN_SLOW_RECOVERY"
WARN_THROTTLE = "WARN_THROTTLE"
WARN_PROMPT_TOKENS = "WARN_PROMPT_TOKENS"
WARN_NO_PROMPT_USAGE = "WARN_NO_PROMPT_USAGE"
WARN_SHORT_WINDOW = "WARN_SHORT_WINDOW"
OUTLIER = "OUTLIER"

# Point classifications.
VALID = "VALID"
VALID_WITH_RERUNS = "VALID_WITH_RERUNS"
UNSTABLE = "UNSTABLE"
FAILED = "FAILED"            # not enough successful reps
NOT_RUN = "NOT_RUN"

VALID_CLASSES = {VALID, VALID_WITH_RERUNS}
