#!/usr/bin/env bash
# Set up vLLM (CPU) twice, without sudo, in micromamba envs:
#   $ZEN_ENV : vLLM CPU wheel + zentorch built from source (auto-discovered platform plugin)
#   $CPU_ENV : same vLLM CPU wheel, no zentorch (stock CpuPlatform baseline)
# and write runtime env files env-zentorch.sh / env-cpu.sh next to them. Idempotent.
#
# Usage: scripts/setup_vllm.sh [--only zentorch|cpu] [--no-models] [--rebuild-zentorch]
# Env:   VLLM_BASE (~/vllm-zen)  VLLM_VERSION (0.28.0)  ZENTORCH_REPO (public amd/ZenDNN-pytorch-plugin)
#        ZENTORCH_REF (zentorch-2026-WW38)  MODELS_DIR (~/mkumar/models)  MAX_JOBS (64)
set -euo pipefail

BASE=${VLLM_BASE:-$HOME/vllm-zen}
VLLM_VERSION=${VLLM_VERSION:-0.28.0}
ZENTORCH_REPO=${ZENTORCH_REPO:-https://github.com/amd/ZenDNN-pytorch-plugin.git}
ZENTORCH_REF=${ZENTORCH_REF:-zentorch-2026-WW38}
ZEN_ENV=${ZEN_ENV:-$BASE/env}
CPU_ENV=${CPU_ENV:-$BASE/env-cpu}
MODELS_DIR=${MODELS_DIR:-$HOME/mkumar/models}
export MAX_JOBS=${MAX_JOBS:-64}
PYVER=3.12
MAMBA=$HOME/.local/bin/micromamba
export MAMBA_ROOT_PREFIX=${MAMBA_ROOT_PREFIX:-$HOME/micromamba}

ONLY="" GET_MODELS=1 REBUILD=0
while [ $# -gt 0 ]; do
  case $1 in
    --only) ONLY=$2; shift ;;
    --no-models) GET_MODELS=0 ;;
    --rebuild-zentorch) REBUILD=1 ;;
    -h|--help) sed -n '2,10p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
  shift
done
want() { [ -z "$ONLY" ] || [ "$ONLY" = "$1" ]; }

log() { printf '[%(%H:%M:%S)T] %s\n' -1 "$*"; }
die() { log "ERROR: $*"; exit 1; }
ver_ge() { [ "$(printf '%s\n%s\n' "$1" "$2" | sort -V | head -n1)" = "$2" ]; }  # $1 >= $2
mkdir -p "$BASE"

# --- vLLM CPU wheel URL (glibc tag: 2_35 for <0.21, 2_34 for 0.21+, 2_39 for 0.30+) ------------------
wheel=$(curl -fsSL "https://api.github.com/repos/vllm-project/vllm/releases/tags/v$VLLM_VERSION" 2>/dev/null |
  python3 -c "import json,sys;print(next(a['name'] for a in json.load(sys.stdin)['assets'] if '+cpu-cp38-abi3-manylinux' in a['name'] and a['name'].endswith('x86_64.whl')))" 2>/dev/null) || wheel=""
if [ -z "$wheel" ]; then
  if ver_ge "$VLLM_VERSION" 0.30.0; then tag=2_39; elif ver_ge "$VLLM_VERSION" 0.21.0; then tag=2_34; else tag=2_35; fi
  wheel="vllm-${VLLM_VERSION}+cpu-cp38-abi3-manylinux_${tag}_x86_64.whl"
fi
WHEEL_URL="https://github.com/vllm-project/vllm/releases/download/v${VLLM_VERSION}/${wheel}"
need_glibc=$(sed -E 's/.*manylinux_([0-9]+)_([0-9]+)_.*/\1.\2/' <<<"$wheel")
have_glibc=$(ldd --version | head -n1 | grep -oE '[0-9]+\.[0-9]+$')
ver_ge "$have_glibc" "$need_glibc" || die "$wheel needs glibc $need_glibc, system has $have_glibc; pick an older VLLM_VERSION"
log "vLLM wheel: $wheel"

# --- micromamba -------------------------------------------------------------------------------------
if [ ! -x "$MAMBA" ]; then
  log "installing micromamba to $MAMBA"
  mkdir -p "$HOME/.local"
  curl -fsSL https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xj -C "$HOME/.local" bin/micromamba
fi

# gperftools = tcmalloc, llvm-openmp = libiomp5 (both preloaded at runtime); gcc/gxx only needed to build zentorch.
mk_env() {  # mk_env <prefix> [extra conda pkgs...]
  local prefix=$1; shift
  if [ -x "$prefix/bin/python" ]; then log "env exists: $prefix"; return; fi
  log "creating env $prefix"
  "$MAMBA" create -y -q -p "$prefix" -c conda-forge "python=$PYVER" gperftools "llvm-openmp=18.1.8" "$@" >/dev/null
}

install_vllm() {  # install_vllm <prefix>
  local py=$1/bin/python cur
  cur=$("$py" -m pip show vllm 2>/dev/null | awk '/^Version:/{print $2}') || true
  if [ "$cur" = "${VLLM_VERSION}+cpu" ]; then log "vllm $cur already in $1"; return; fi
  log "installing vllm $VLLM_VERSION into $1"
  "$py" -m pip install -q --upgrade pip
  # torch comes from the vLLM wheel's pins; installing torch separately breaks the ABI match.
  "$py" -m pip install -q "$WHEEL_URL" --extra-index-url https://download.pytorch.org/whl/cpu
}

write_env_file() {  # write_env_file <file> <prefix> <label>
  cat > "$1" <<EOF
# source $1  -- $3 (vLLM $VLLM_VERSION CPU), generated by setup_vllm.sh
export CONDA_PREFIX=$2
export PATH=\$CONDA_PREFIX/bin:\$PATH
export LD_PRELOAD="\$CONDA_PREFIX/lib/libiomp5.so:\$CONDA_PREFIX/lib/libtcmalloc_minimal.so.4\${LD_PRELOAD:+:\$LD_PRELOAD}"
export VLLM_CPU_KVCACHE_SPACE=\${VLLM_CPU_KVCACHE_SPACE:-90}
# physical cores of one socket; lscpu -e shows the layout
export VLLM_CPU_OMP_THREADS_BIND=\${VLLM_CPU_OMP_THREADS_BIND:-0-95}
# FREEZING=1 without AOT_COMPILE=0 crashes engine-core init
export TORCHINDUCTOR_FREEZING=\${TORCHINDUCTOR_FREEZING:-1}
export VLLM_USE_AOT_COMPILE=\${VLLM_USE_AOT_COMPILE:-0}
if [ -z "\${HF_TOKEN:-}" ] && [ -s "\$HOME/.cache/huggingface/token" ]; then export HF_TOKEN=\$(<"\$HOME/.cache/huggingface/token"); fi
EOF
}

# --- vLLM + zentorch --------------------------------------------------------------------------------
if want zentorch; then
  mk_env "$ZEN_ENV" gcc=12 gxx=12
  install_vllm "$ZEN_ENV"

  src=$BASE/zentorch-src
  if [ ! -d "$src/.git" ]; then
    log "cloning $ZENTORCH_REPO"
    git clone -q "$ZENTORCH_REPO" "$src"
  fi
  git -C "$src" fetch -q --tags origin 2>/dev/null || true
  git -C "$src" checkout -q "$ZENTORCH_REF"
  head=$(git -C "$src" rev-parse HEAD)

  init=$src/src/cpu/python/zentorch/vllm/__init__.py
  vmin=$(sed -nE 's/^VLLM_MIN_VERSION = "(.*)"/\1/p' "$init")
  vmax=$(sed -nE 's/^VLLM_MAX_VERSION = "(.*)"/\1/p' "$init")
  if [ -n "$vmin" ] && ! { ver_ge "$VLLM_VERSION" "$vmin" && ver_ge "$vmax" "$VLLM_VERSION"; }; then
    die "zentorch $ZENTORCH_REF supports vLLM $vmin..$vmax, not $VLLM_VERSION"
  fi
  log "zentorch $ZENTORCH_REF ($head) supports vLLM ${vmin:-?}..${vmax:-?}"

  built=$(cd /tmp && "$ZEN_ENV/bin/python" -c 'import torch, zentorch; print(zentorch.__config__)' 2>/dev/null |
    sed -nE 's/.*Commit-id: *([0-9a-f]+).*/\1/p') || true
  if [ "$built" = "$head" ] && [ $REBUILD = 0 ]; then
    log "zentorch at $head already installed"
  else
    log "building zentorch (log: $BASE/zentorch_build.log)"
    "$ZEN_ENV/bin/python" -m pip install -q -r "$src/requirements.txt"
    (
      cd "$src" && rm -rf build dist
      # Without an activated conda env the conda linker cannot find the env's libstdc++ (aoclutils examples fail).
      export PATH=$ZEN_ENV/bin:$PATH CC=$ZEN_ENV/bin/gcc CXX=$ZEN_ENV/bin/g++
      export LDFLAGS="-L$ZEN_ENV/lib -Wl,-rpath-link,$ZEN_ENV/lib -Wl,-rpath,$ZEN_ENV/lib"
      python setup.py bdist_wheel
    ) > "$BASE/zentorch_build.log" 2>&1 || { tail -n 30 "$BASE/zentorch_build.log"; die "zentorch build failed"; }
    "$ZEN_ENV/bin/python" -m pip install -q --no-deps --force-reinstall "$src"/dist/zentorch-*.whl
  fi

  write_env_file "$BASE/env-zentorch.sh" "$ZEN_ENV" "vLLM + zentorch"
  out=$(cd /tmp && source "$BASE/env-zentorch.sh" && python -c "from vllm import LLM" 2>&1) || { echo "$out"; die "vllm import failed"; }
  grep -q "Platform plugin zentorch is activated" <<<"$out" || { echo "$out"; die "zentorch plugin not activated"; }
  log "verified: zentorch platform plugin activates in $ZEN_ENV"
fi

# --- vLLM stock CPU (no zentorch) -------------------------------------------------------------------
if want cpu; then
  mk_env "$CPU_ENV"
  install_vllm "$CPU_ENV"
  write_env_file "$BASE/env-cpu.sh" "$CPU_ENV" "vLLM stock CPU, no zentorch"
  out=$(cd /tmp && source "$BASE/env-cpu.sh" && python -c "
import importlib.util
from vllm.platforms import current_platform
assert importlib.util.find_spec('zentorch') is None, 'zentorch is installed in the baseline env'
print('PLATFORM', type(current_platform).__name__)" 2>&1) || { echo "$out"; die "baseline env check failed"; }
  grep -q "PLATFORM CpuPlatform" <<<"$out" || { echo "$out"; die "baseline env is not on CpuPlatform"; }
  log "verified: $CPU_ENV uses stock CpuPlatform"
fi

# --- model ------------------------------------------------------------------------------------------
if [ $GET_MODELS = 1 ]; then
  dst=$MODELS_DIR/Llama-3.1-8B-Instruct
  hf=$(command -v hf || echo "$CPU_ENV/bin/hf"); [ -x "$hf" ] || hf=$ZEN_ENV/bin/hf
  [ -z "${HF_TOKEN:-}" ] && [ -s "$HOME/.cache/huggingface/token" ] && export HF_TOKEN=$(<"$HOME/.cache/huggingface/token")
  log "downloading meta-llama/Llama-3.1-8B-Instruct -> $dst (resumes / skips complete files)"
  HF_HUB_DISABLE_PROGRESS_BARS=1 "$hf" download meta-llama/Llama-3.1-8B-Instruct --exclude 'original/*' --local-dir "$dst" >/dev/null
fi

cat <<EOF

vLLM $VLLM_VERSION ready:
  with zentorch:    source $BASE/env-zentorch.sh
  without zentorch: source $BASE/env-cpu.sh
  then e.g.: numactl --membind=0 vllm serve $MODELS_DIR/Llama-3.1-8B-Instruct --dtype bfloat16 --port 8000
EOF
